name: 'Build Webpack'
on:
  push:
    branches:
      - development

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout V2'
      uses: actions/checkout@v2
    - name: 'Install Node.js'
      uses: actions/setup-node@v1
    - name: 'NPM Install'
      run: npm install
    - name: 'NPM Build'
      run: npm run prod
    - name: 'Update Sitemap'
      uses: jelleschutter/update-sitemap-action@master
    - name: 'Deploy'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: build




