name: 'Build Webpack'
on:
  push:
    branches:
      - development
  page_build:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout V2'
      uses: actions/checkout@v2
    - name: 'Install Node.js'
      uses: actions/setup-node@v1
    - name: 'NPM Install'
      run: npm install
    - name: 'NPM Build'
      run: npm run prod
    - name: 'Get Date'
      run: echo "::set-env name=currentTime::$(date --iso-8601=seconds)"
    - name: 'Update Sitemap'
      uses: Mudlet/xmlstarlet-action@v1.1
      with:
        args: ed --inplace -N x="http://www.sitemaps.org/schemas/sitemap/0.9" --update "/x:urlset/x:url/x:lastmod" --value "test"  build/sitemap.xml
    - name: 'Deploy'
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: master
        FOLDER: build




