name: 'Build Webpack'
on:
  push:
    branches:
      - master
  page_build:

jobs:
  build:
    name: 'Build'
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout V2'
      uses: actions/checkout@v2
    - name: 'Install Node.js'
      uses: actions/setup-node@v1
    - name: 'NPM Install'
      run: npm install
    - name: 'NPM Build'
      run: npm run prod




